### ISSUE TITLE
Notification for repeated authentication failure requiring manual intervention.

### ISSUE THREAD

**Issue by fancypantsifier** [homebridge-simplisafe3/homebridge-simplisafe3#283] opened 2022-01-17 04:49 UTC
### Is your feature request related to a problem? Please describe:

I bumped into Issue #255 today and it was a bit painful because it meant that my arrival home caused my alarm to go off because my HomeKit automation to disable the alarm based on my presence and the garage door opening did not work since nothing triggering off my Simplisafe sensors was working. It caught by surprise and I'm just glad it was me and not my wife since we've come to trust the automations offered by this awesome plugin. Manual reauthentication seems to have fixed it, and as long as this is infrequent, that's fine, but it would nice to have a heads up something is amiss -- before the alarm triggers!

Is there a way we could get some kind of signal or notification when the plugin needs manual reauthentication (e.g. starts repeatedly receiving this 403 error)? I also use the the dummy switch and messenger plugins for HomeBridge, so something that would allow me to flip a virtual switch that triggers an IFFFT notification would be totally acceptable. I'm happy to open a feature request if this is remotely feasible. Thanks!
(I mentioned this on the Issue thread too, but since it's closed, I'm not sure anyone is paying attention to it anymore. :-)) 

### Describe the solution you'd like:
See above. I'd like to get a notification on my phone when Simplisafe authentication starts failing repeatedly. If using other plugs (dummy switches, messenger, etc) make that possible, I'm fine with that.

### Describe alternatives you've considered:

- Maybe I could make my own dummy switch tied to some Simplisafe device with an automation that runs periodically to do this myself?
- Setting a reminder in my phone to re-authenticate every 30 days, in case this is somehow tied to Simplisafe's (new?) requirement that you login and get a code via text message every 30 days.

### Additional context:

None.

**Comment by shamoon** [comment] 2022-01-17 05:12
Hi @fancypantsifier this actually already exists!  Agree it’s useful. See https://github.com/homebridge-simplisafe3/homebridge-simplisafe3

Duplicate of #264

**Closed by shamoon** 2022-01-17 05:12 UTC
Labels: enhancement

**Comment by fancypantsifier** [comment] 2022-01-17 06:43
Wow, ok, I'm impressed. Again. :-)

Sounds like I'll have to use something other than the native Home app to use it though, huh? So far I've gotten by without any third party apps, but unless there's another Homebridge plugin which can expose custom properties as their own device to HomeKit, I guess that'll be necessary now.

**Comment by fancypantsifier** [comment] 2022-01-17 07:01
Oh wait I think I just found status fault available in shortcut-based automations. Nice!!

**Comment by shamoon** [comment] 2022-01-17 08:15
Yea, Eve app is free tho, and it’s a nice alternative to adding more complexity to automations. I keep it around for just that even if I use Home.app 99% of the time.

**Comment by fancypantsifier** [comment] 2022-01-17 17:17
Seems like I can do it from Home app natively. Is this not what I want?

![image](https://user-images.githubusercontent.com/8006003/149812564-c9252000-6fad-41d9-88b2-40a2c39d262f.jpeg)

Note that "Simplisafe Auth Fail" is an IFFFT message "switch" from the [homebridge-messenger plugin](https://github.com/potrudeau/homebridge-messenger).

I am actually using Eve to schedule to run repeatedly on a timer, since I don't think the Home app supports that. Ironically, I could not find how to access that Status Fault from Eve though.

**Comment by shamoon** [comment] 2022-01-18 00:14
Looks good
