### ISSUE TITLE
[BUG] Plugin Fails to Update

### ISSUE THREAD

**Issue by elcid2012** [homebridge-simplisafe3/homebridge-simplisafe3#335] opened 2022-04-15 15:58 UTC
### Description

USER: root
DIR: /homebridge
CMD: npm install --save homebridge-simplisafe3@latest

npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! process terminated
npm ERR! signal SIGTERM

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-15T15_35_40_844Z-debug-0.log

Command failed. Please review log for details.

[2022-04-15T15_35_40_844Z-debug-0.log](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/files/8496834/log.log)

### Expected behavior

Plugin upgrades without error.

### Steps to reproduce

Run Homebridge in Docker. Go to Plugins, click "Update" under Homebridge Simplisafe3.

### Homebridge logs

```bash
Corresponding log file is attached in Description section.
```

### Homebridge config.json contents

```json
{
            "name": "Simplisafe 3",
            "cameras": false,
            "debug": true,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "_bridge": {
                "username": "<redacted>",
                "port": 57212
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        },
```

### Plugin version

1.9.11

### Homebridge version

1.4.0

### Node.js version

16.14.2

### Host OS

Raspbian

**Comment by shamoon** [comment] 2022-04-15 20:50
I’m not able to reproduce this. Those errors shouldn’t cause install to fail. What does that log file that it’s telling you about show?

**Comment by elcid2012** [comment] 2022-04-15 21:02
It's attached to the description in this issue, but I believe the relevant portion is:

`2985 verbose stack Error: process terminated
2985 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:197:39
2985 verbose stack     at process.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
2985 verbose stack     at process.emit (node:events:538:35)
2986 verbose cwd /homebridge
2987 verbose Linux 5.15.32-v8+
2988 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "homebridge-simplisafe3@latest"
2989 verbose node v16.14.2
2990 verbose npm  v8.5.0
2991 error process terminated
2992 error signal SIGTERM
2993 verbose exit 1
2994 timing npm Completed in 445975ms
2995 verbose unfinished npm timer reify 1650036944626
2996 verbose code 1
2997 error A complete log of this run can be found in:`

**Comment by shamoon** [comment] 2022-04-15 23:53
Ah, missed the attachment. I have no idea what that error means. Do you have that problem with other plugins? Honestly I wouldn't guess the problem is with this plugin but something about your install, perhaps the docker image (I use docker on a different OS).

Quick google yields:

- https://stackoverflow.com/questions/13443526/npm-installs-all-modules-in-usr-local-lib-node-modules
- https://github.com/homebridge/homebridge/issues/3020

Looks like re-installing node, or in your case presumably the docker image. Again, not aware of any actual issues like that with this plugin.

**Comment by shamoon** [comment] 2022-04-15 23:55
Ps. SD cards in RPis get corrupted all the time, could be related. Its throwing directory errors too, `verbose cwd /homebridge`

**Comment by elcid2012** [comment] 2022-04-16 00:36
Copy. I think I know what I may have done and this is on my end (as usual). I thought it was odd I was able to update other plugins today but not SimpliSafe.

 Going to backup and delete the image and data folder, then start fresh and restore from backup. Will report back once I’ve done this.

**Comment by elcid2012** [comment] 2022-04-17 18:30
No dice. Thought I would uninstall the plug in completely and re-install it. It no longer reinstalls without hanging up the entire RPi 3 and forcing me to reboot via PoE power cycling.

Not sure it's actually a card issue because I updated HB-UI and HB Plugin Check right before attempting to update this plugin in my initial post; both were successful.

**Comment by shamoon** [comment] 2022-04-17 18:47
Can you install other plugins? How about older versions of this one?

**Comment by shamoon** [comment] 2022-04-17 19:00
For example 1.9.11 is before the recent dependency updates

**Comment by elcid2012** [comment] 2022-04-17 19:11
Yep, tracking. Installing another plugin was unsuccessful (it was also throwing warnings and errors, may have just been the plugin itself), so I restored from a backup from 13 April my /homebridge directory (docker). Immediately was able to update plugin-update-check again.

For Simplisafe3 update... Threw the same warnings as before, plugin was unsuccessful to update. I'm going to go back one more day (12 April) and see if that makes a difference.

**Comment by elcid2012** [comment] 2022-04-17 19:29
Upon restoring to (actually) my 11 April backup file:

Simplisafe 3 threw authentication error, so I re-authenticated and restarted the HB process as required.

plugin-update-check was out of date as expected, and I was successful in updating that once again to the latest version.

Simplisafe3 plugin update... takes forever... same warnings. Failed again.

11 April I know for sure I had a good working config and running HB instance. Only difference I can think of is the UI was on a previous version. Either it's that, or this is maybe an RPi 3 thing with ffmpeg. I don't need ffmpeg anyway because I'm not using SS's cameras.

**Comment by shamoon** [comment] 2022-04-17 19:36
Are you saying that version of the plugin works? Which version?
Are you running a Pi3/3b/3b+?  What version of Raspian?

I just confirmed again this installed OK (yes took a while) on my RPi3b+ running Bullseye...

**Comment by elcid2012** [comment] 2022-04-17 19:39
`cat /proc/cpuinfo`
`Raspberry Pi 3 Model B Rev 1.2`

`cat /etc/os-release`
`PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"`

**Comment by elcid2012** [comment] 2022-04-17 19:40
UI rollback to v4.42 wasn't successful.

I think this is a me problem...

**Comment by shamoon** [comment] 2022-04-17 20:04
Ok. I also created a beta `1.10.4-beta.1` which also installs OK for me, I doubt will make a difference but you can try that. Though again, it sounds like something else going on...

**Comment by elcid2012** [comment] 2022-04-17 20:30
Yeah that failed too. Going to try one more thing. Fresh HB docker and try installing the plugin without a HB restore.

Otherwise, going to just do a Raspbian OS reinstall since that seems to be the quickest way to fix crap on Linux. I probably fat-fingered some `mv` command and broke something.

**Comment by elcid2012** [comment] 2022-04-17 20:42
Well... that didn't work, actually. So I'm not sure what's going on at this point. I got two new warnings on this go:

USER: root
DIR: /homebridge
CMD: npm install --save homebridge-simplisafe3@latest

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! process terminated
npm ERR! signal SIGTERM

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-17T20_32_44_927Z-debug-0.log

Command failed. Please review log for details.

Anyway, I am going to restore as things were and leave this alone for now instead of reinstalling Raspbian. Let me know if I can provide you with additional log files.

**Comment by shamoon** [comment] 2022-04-17 20:44
Those are warnings, they shouldnt stop the install. `/root/.npm/_logs/2022-04-17T20_32_44_927Z-debug-0.log` could be helpful but it might just be similar to before.

**Comment by elcid2012** [comment] 2022-04-17 20:52
So get this... simplisafe3 v1.9.11 installed just fine on a fresh HB docker (no restore from backup).

Here's that log file from my last post:
[2022-04-17T20_32_44_927Z-debug-0.log](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/files/8502419/2022-04-17T20_32_44_927Z-debug-0.log)

**Comment by shamoon** [comment] 2022-04-17 21:14
Well Im afraid to ask what happens if you try to upgrade. But also could try the beta...  That log doesnt make sense to me, it says completed and then process terminated. Have you tried `npm install --unsafe-perm homebridge-simplisafe3`? Hoenstly Im a bit stumped

**Comment by elcid2012** [comment] 2022-04-17 23:35
> `npm install --unsafe-perm homebridge-simplisafe3`

That did the trick from within `docker exec` and I’m now on 1.10.3.

**Comment by elcid2012** [comment] 2022-04-18 12:08
Somehow I missed the upgrade from 1.9.11 to 1.10.2. Is it possible there's not a direct upgrade path from 1.9.11 to 1.10.3? Still doesn't explain why 1.10.3 wouldn't install for me on a fresh HB installation, though.

**Comment by lingrlongr** [comment] 2022-04-21 13:53
same problem.  beta version results in errors too.

[2022-04-17T20_32_44_927Z-debug-0.log](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/files/8531544/2022-04-17T20_32_44_927Z-debug-0.log)

**Comment by shamoon** [comment] 2022-04-21 16:47
Can you guys try [`1.10.4-beta.3`](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/releases/tag/v1.10.4-beta.3)?

**Comment by elcid2012** [comment] 2022-04-21 20:13
Successfully updated from 1.10.3 to 1.10.4-beta.3.

Do you want me to try anything else?

Also npm threw a notice that it needs updating from 8.5.0 to 8.7.0. I assume that gets updated through the docker container at some point.

**Comment by shamoon** [comment] 2022-04-21 20:17
Nope, thats great! @lingrlongr if you can confirm the same I can release beta-3 as a fix, thank you.

Yes, npm is part of the docker container presumably

**Comment by lingrlongr** [comment] 2022-04-22 15:36
i tried beta3, but still getting errors.  i tried updating to npm 8.7.0 too.  here's the log:
[2022-04-22T14_44_38_733Z-debug-0.log](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/files/8542207/2022-04-22T14_44_38_733Z-debug-0.log)

**Comment by shamoon** [comment] 2022-04-22 16:14
Ugh, sorry that beta is mis-tagged. I don’t have full admin to npm so I will release a new one soon. I do think I have the issue sorted tho. Thanks for your patience.

**Comment by shamoon** [comment] 2022-04-22 16:57
Ok @lingrlongr please try [beta.4](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/releases/tag/v1.10.4-beta.4). Im not on my home machine but looks like that beta should actually contain the fix I was meaning it to.

**Comment by lingrlongr** [comment] 2022-04-22 17:04
beta4 did the trick!  thx @shamoon!

**Comment by shamoon** [comment] 2022-04-22 17:05
Oh great, thanks!

**Comment by elcid2012** [comment] 2022-04-22 17:11
Updated to 1.10.4-beta.4 as well without issue.

**Comment by shamoon** [comment] 2022-04-22 17:11
Closed by https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/commit/57a941249f63c84406e27943f8f63c88092e9d17

**Closed by shamoon** 2022-04-22 17:11 UTC
Labels: not a bug
